---

-  name: Change hostname
   gather_facts: no
   hosts: all
   tasks:
     - name: change hostname to localhost
       hostname:
         name: "localhost"
         use: systemd

#    дебаг, можно закомментить
     - shell: hostname
       register: final_hostname

     - debug: 
         msg:
           - "hostname is {{ final_hostname.stdout }}"